name: CI/CD workflow
on: push

jobs:
    build-frontend-and-node-api:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            include:
              - context_name: ./frontend
                image_name: ghcr.io/ennaelle/cicd2/frontend
              - context_name: ./node-api
                image_name: ghcr.io/ennaelle/cicd2/node-api
        permissions:
            packages: write
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: setup QEMU
              uses: docker/setup-qemu-action@v3
            - name: setup buildx
              uses: docker/setup-buildx-action@v3
            - name: docker login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: build and push
              uses: docker/build-push-action@v5
              with:
                context: ${{ matrix.context_name }}
                push: true
                tags: ${{ matrix.image_name }}:latest
                cache-from: type=gha
                cache-to: type=gha, mode=max