name: CI/CD workflow
on: push

jobs:
    build-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: setup QEMU
              uses: docker/setup-qemu-action@v3
            - name: setup buildx
              uses: docker/setup-buildx-action@v3
            - name: docker login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: build and push
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                push: true
                tags: ghcr.io/ennaelle/cicd2/frontend:latest